### ISSUE TITLE
LG open-sourced the EXAONE 3.0 7.8B instruction-tuned model 

### ISSUE THREAD

**Issue by Amy-Min11** [NHLOCAL/AiTimeline#4]
Aug 7th 2024, LG released its third version of the multimodal model, EXAONE 3.0 and open-sourced 7.8B instruction-tuned model.

EXAONE 3.0 7.8B has achieved a global top level performance in both English and Korean compared to other global models of similar size. Model focuses on practical features and real-world use cases that can enhance productivity, particularly in instruction following, role-playing, math & coding, and reasoning. 

- Technical Report : https://arxiv.org/abs/2408.03541
- Model on GitHub : https://github.com/LG-AI-EXAONE
- Gradio Demo : https://lnkd.in/gpxsRs6W

**Comment by NHLOCAL** [comment]
It does not seem that the model received significant publicity, we focus mainly on the most prominent developments in the field
Thanks for the update anyway!
