### ISSUE TITLE
עדכון מאנתרופיק

### ISSUE THREAD

**Issue by Y-PLONI** [NHLOCAL/AiTimeline#5]
המייל שקיבלתי:
שלום,

לאחרונה הכרזנו על סונטה מעודנת של קלוד 3.5 - זמינה כעת לשימושך ב- [Claude.ai](https://links.iterable.com/u/click?_t=67101f7d500248b386768eecaae4611b&_m=b31b3ac6f9fe426bbcb44501cbd59540&_e=Rdj9B5KLZwlK5n0h2JRozgYmkSKRRm02RUU5qsoJ5zQXLnkff2ILE3DE7Y8D9hWxCAcAFGdkMdvdy6wvkUiaYDW_PM9YEM294rSMTFoK9ZjiKXMDH22R-d9tER6fBYgk7YDE9qc5PNGPgpy2DyCj2hCQncddWfzU1w6Xwle9Nc4WTMRz_P_qp19LEKMQEnoE7XczTMAAudBXQK3uuDHMPf-ufdF7E_iMgJnOiV-re_RIi3SkuoQ48lUhiZCFyIp6xiNMgUaXE7Vis21zSaK-tkpCAb1eBJi8XlkQ1z5HdjQAYcTODQYUYfUqmYgSy8Wx42v21SlgNC9XctAYhv48jg%3D%3D) .

הגרסה העדכנית ביותר של קלוד 3.5 Sonnet היא עדכנית למשימות הנדסת תוכנה. הוא מציע גם חשיבה משופרת, פתרון בעיות יצירתי יותר והבנת הקשר יותר ניואנסים.

בנוסף לקלוד 3.5 Sonnet, הכרזנו על יכולת שימוש ניסיוני במחשב בבטא ציבורית ב-Anthropic API, Amazon Bedrock ו-Google Vertex AI. שיתפנו גם שקלוד 3.5 הייקו מגיע בקרוב. למידע נוסף [בפוסט בבלוג](https://links.iterable.com/u/click?_t=67101f7d500248b386768eecaae4611b&_m=b31b3ac6f9fe426bbcb44501cbd59540&_e=Rdj9B5KLZwlK5n0h2JRoztiMe6RehFDwffxgnTe6cvEQEkoGo6ke34lKfBss0SB74J52AXC030I2g9VQY6nKsYjAzEYvSPuB3Wa_UEtQqdlISefEpNDqY--cO6V8vRl1RVZmCa5-xmkPG4iw2DpdsKxmgFd2hl0NEfxWX9UswD2DCfoGiDlEWWVnBGI6gzNmxXLhtQGNdBJIoDrfup-zqjsbxQPGw-ezSPNbHScrE8ETUIwwPIUjQ7m6oMrlCnC9A8TW7tc2hLugauHc532DyK2ZX6R9BuS08hkqOrCMWD8KOSGf_be-DmKuH-uwkSGkbq9z95QnWtcGS5sG4U4CtuIwcUIi9_Xl6VcM01rl8wtyJ6FpVTdcXCGoFdMjEw8elC7tSnUuIENlLOb9V9WmTA%3D%3D) שלנו.

בנוסף, תיקון קל:
[למנויים](https://nhlocal.github.io/AiTimeline/#2024:~:text=%D7%94%D7%9E%D7%AA%D7%A7%D7%93%D7%9D%20%D7%A9%D7%9C%20GPT4o-,%D7%9C%D7%9B%D7%9C%20%D7%94%D7%9E%D7%A0%D7%95%D7%99%D7%99%D7%9D.,-%D7%9E%D7%98%D7%90%20%D7%9E%D7%A9%D7%99%D7%A7%D7%94%20%D7%90%D7%AA)

**Comment by NHLOCAL** [comment]
אני עוקב צמוד אחרי כל ההתפתחויות... אני יוסיף את זה לקראת סוף החודש הלועזי עם עוד הרבה מאוד עדכונים
(נראה לי אחד החודשים העמוסים בתחום אי פעם...)
ראה [כאן ](https://github.com/NHLOCAL/AiTimeline/blob/9906939d75947f716b0c3d28641656c0a1c4c368/create-info/input.txt)

**Comment by Y-PLONI** [comment]
יש קישור למילה המדויקת, לא?

‫בתאריך יום ה׳, 31 באוק׳ 2024 ב-20:28 מאת ‪NHLOCAL‬‏ <‪
***@***.***‬‏>:‬

**Comment by NHLOCAL** [comment]
לא. שים לב שהאתר הוא למעשה באנגלית. תן קישור לתוכן כפי שהוא באנגלית

**Comment by Y-PLONI** [comment]
צודק.
בשעתו שמתי לב לזה, ו'בדקתי' שהקישור הוא למילי באנגלית...
אגב, המודל של MS [PHI3] לא כזה ממוצלח כמו שאתה עושה אותו... לפחות בעברית...

**Comment by NHLOCAL** [comment]
אגב, המודל של MS [PHI3] לא כזה ממוצלח כמו שאתה עושה אותו... לפחות בעברית...

ברור שלא. והוא גם לא נועד להיות. הוא מיועד רק עבור אנגלית. כדאי לקרוא את המידע על המודל לפני שמורידים אותו...

כיום יש כבר הרבה מודלים בגודל הזה ברמה טובה לא פחות. אבל בזמנו זה היה פורץ דרך
